spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts"
  contactDetails:
    name: "Figge Strandberg - QA lead"
    email: "figge@eazybank.com"
  onCallSupport:
    - (666)666-1234
    - (666)623-1345