server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: JonathanKom07
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  ### sql:
      ###  init:
    ###mode: always
      ###hibernate:
      ###ddl-auto: update
    ###show-sql: true
