server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: JonathanKom07
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
