spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards"
  contactDetails:
    name: "John Tester - QA lead"
    email: "johnT@eazybank.com"
  onCallSupport:
    - (666)666-1234
    - (666)623-1345