spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards"
  contactDetails:
    name: "John PO - Product Owner"
    email: "johnP@eazybank.com"
  onCallSupport:
    - (777)777-1234
    - (777)723-1345