server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"
# server:
#   port: 9000
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/cardsdb
#     driverClassName: com.mysql.jdbc.Driver
#     username: root
#     password: JonathanKom07
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345